version: '3.8'

services:
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    container_name: realtime_chat_auth
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
    networks:
      - realtime_chat_net

  # Infra
  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    healthcheck:
      test: pg_isready -q -d chatdb -U chatuser
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5432:5432'
    networks:
      - realtime_chat_net
    volumes:
      - realtime_chat_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq
    container_name: realtime_chat_rabbitmq
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '5672:5672'
    volumes:
      - realtime_chat_broker:/var/lib/rabbitmq/mnesia/
    networks:
      - realtime_chat_net

  elasticsearch:
    image: elasticsearch:8.9.2
    container_name: elasticsearch
    environment:
      - 'ES_JAVA_OPTS=-Xms1g -Xmx1g'
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - realtime_chat_es_data:/usr/share/elasticsearch/data
      - ./configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - realtime_chat_net
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'curl -u ${ELASTIC_SEARCH_USER}:${ELASTIC_SEARCH_PASSWORD} localhost:9200/_cluster/health || exit 1',
        ]
      interval: 15s
      timeout: 5s
      retries: 5

  # Utility
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - '8080:80'
    networks:
      - realtime_chat_net
    depends_on:
      postgres:
        condition: service_healthy

  kibana:
    image: kibana:8.9.2
    container_name: kibana
    ports:
      - 5601:5601
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - ./configs/kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      - realtime_chat_net

volumes:
  realtime_chat_data:
    name: realtime_chat_data
  realtime_chat_broker:
    name: realtime_chat_broker
  realtime_chat_es_data:
    name: realtime_chat_es_data

networks:
  realtime_chat_net:
    name: realtime_chat_net
    driver: bridge
