export const MessagePatterns = {
  AUTHENTICATE: 'AUTHENTICATE',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOOKUP: 'USER_LOOKUP',
  CONVERSATION_MESSAGE: 'CONVERSATION_MESSAGE',
  CONVERSATION_LOOKUP: 'CONVERSATION_LOOKUP',
} as const;
