export const MessagePatterns = {
  AUTHENTICATE: 'AUTHENTICATE',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOOKUP: 'USER_LOOKUP',
  CREATE_CONVERSATION_MESSAGE: 'CREATE_CONVERSATION_MESSAGE',
  CONVERSATION_LOOKUP: 'CONVERSATION_LOOKUP',
} as const;
